### ISSUE TITLE
CCScrollLayer: Possible break Fix if CCTouchDispatcher will be changed.

### ISSUE THREAD

**Issue by psineur** [cocos2d/cocos2d-iphone-extensions#97]
Thankfully to @SG7, possible break of CCScrollLayer (if this pull request get merged: https://github.com/cocos2d/cocos2d-iphone/pull/171 ) can be easily fixed like this:

```
    //- (NSMutableArray *) targetedHandlers;
    - (CCArray   *) targetedHandlers;

    @end

    @implementation CCTouchDispatcher (targetedHandlersGetter)

    //- (NSMutableArray *) targetedHandlers
    - (CCArray   *) targetedHandlers
    {
     return targetedHandlers;
    }

    @end // and the only place when internal array is used:

    //  for ( CCTargetedTouchHandler *handler in [[CCTouchDispatcher sharedDispatcher] targetedHandlers] )

     CCTargetedTouchHandler *handler;
     CCArray array = [[CCTouchDispatcher sharedDispatcher] targetedHandlers];
     CCARRAY_FOREACH(array, handler) {
     //...
     }
```

**Comment by SG7** [comment]
@psineur Thanks for your comment and extensions!
It looks like only your CCScrollLayer uses private internals of CCTouchDispatcher via category.
I can also let you know when this pull gets merged. 

The change of the container to CCArray allowed significant speed improvements
 and it is in line with the rest of the cocos2d code.  

Without running the test suit it is hard to see most of the benefits of the new TouchDispatcher.

This is just one example:

|---------------------------------------------------------------------|
|   Hardware: latest iPod4                                            |
|                                                                     |
|   SPEED TEST:  (5) && (5.c) in the test suite                       |
|                                                                     |
| Changing priorities of the touch handlers                           |
| (50% standard 50% targeted).                                        | 
|---------------------------------------------------------------------|
1. FPS (Frame rate per second)
   |=====================================================================|
   |       Changing priorities   (FPS)                                   |
   |=====================================================================|
   |     NR       |     CURRENT    |             NEW DISPATCHER          |
   |  OF HANDLERS |   DISPATCHER   | Same API fun. | added API function  |
   |=====================================================================|  
   |      200     |       13.2     |       34\*     |        60  FPS      |
   |--------------|------------------------------------------------------|
   |      400     |       3.7      |       11\*     |        38  FPS      |
   |---------------------------------------------------------------------|
   |      600     |       1.6      |       5.5\*    |        20  FPS      |
   |---------------------------------------------------------------------|
- in a touch callbacks the FPS increases to the value in the right column
  due to internal optimization. 
  1. Speed (in milliseconds) 
     |=====================================================================|
     |       Changing priorities    (ms)                                   |
     |=====================================================================|
     |     NR       |     CURRENT    |             NEW DISPATCHER          |
     |  OF HANDLERS |   DISPATCHER   | Same API fun.   | added API function|
     |=====================================================================|  
     |      200     |        55      |       13.6\*     |      4.7  ms      |
     |--------------|------------------------------------------------------|
     |      400     |       212      |       47.7\*     |     16.6  ms      |
     |---------------------------------------------------------------------|
     |      600     |       485      |      100.5\*     |     31.7  ms      |
     |---------------------------------------------------------------------|
- in a touch callbacks the speed increases and time drops to the value
  specified the right column due to specifics of the internal algorithm 
  improvements.

**Comment by psineur** [comment]
Pull Request integrated to the develop branch of cocos2d-iphone: https://github.com/cocos2d/cocos2d-iphone/pull/183

**Comment by psineur** [comment]
More commits regarding this issue: 
1. 1acdba979526b101208c83be490a03be35e2c944
2. 451427bc4333c9589826d9e7ca19f5d7f631fe7b

Fixed, sideeffect - all other targetedDelegates, that have claimed touches are better robbed now - no need to deselect menuItems manually - this is done through calling ccTouchCancelled:event:

**Comment by SG7** [comment]
@psineur your enumeration protocol :  id NSFastEnumeration

(id<NSFastEnumeration>) targetedHandlers {
    return targetedHandlers;
}

is brilliant fix providing backward compatibility at the same time!
